title: RTK FULL
author: Mạnh Tài
url: http://manhtai.github.io/rtk
description: "Remembering the Kanji: rtk.manhtai.com"

permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
